program: train.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  epochs:
    values: [5, 10]
  batch_size:
    values: [4, 16, 32, 64]
  loss:
    values: ["mean_squared_error", "cross_entropy"]
  optimizer:
    values: ["sgd", "momentum", "adam", "rmsprop", "nadam"]
  learning_rate:
    values: [0.001, 0.0001]
  weight_decay:
    values: [0, 0.0005, 0.5]
  weight_init:
    values: ["random", "xavier"]
  num_layers:
    values: [3, 4, 5]
  hidden_size:
    values: [32, 64, 128]
  activation:
    values: ["identity", "sigmoid", "tanh", "ReLU"]
